#!/usr/bin/env bash

# A simple scrollable list navigator.
# Usage: garden nav

items=("help" "version" "paths" "init" "status" "profile" "log" "events" "metrics" "weave" "inspect" "palette" "search" "shell")
index=0

draw() {
  clear
  echo "🌿 Garden Navigator"
  echo "Use j/k to move, enter to select, q to quit."
  echo ""

  for i in "${!items[@]}"; do
    if [ "$i" -eq "$index" ]; then
      printf "> %s\n" "${items[$i]}"
    else
      printf "  %s\n" "${items[$i]}"
    fi
  done
}

draw

while true; do
  read -rsn1 key

  case "$key" in
    j)
      ((index++))
      ((index >= ${#items[@]})) && index=$((${#items[@]} - 1))
      draw
      ;;
    k)
      ((index--))
      ((index < 0)) && index=0
      draw
      ;;
    "")
      clear
      echo "Running: ${items[$index]}"
      garden "${items[$index]}"
      echo ""
      read -p "Press any key to return..." -n1
      draw
      ;;
    q)
      clear
      exit 0
      ;;
  esac
done
